
var WebShakes = (function(){
  
  	var patterns  = [];
	var providers = [];
	var providersMap = {};

	function loadProviders() {
		providers[0] = GM_provider;
		//providers[1] = STYLISH_provider;
		for (var i=0; i<providers.length; i+=1) {
			var extensions = providers[i].getMixFileExtensions();
			
			for(var j=0; j<extensions.length; j+=1) {
				patterns[patterns.length] = extensions[j];
				providersMap[extensions[j]] = providers[i];
			}
		}
	}
  
	// Ctor
	loadProviders();
  
    var obj = {

		//---------------------------------
		// ---------  Inner API   --------
		//---------------------------------
		toggleEnableMix: function (mixId) {
			GM_provider.toggleEnable(mixId);
		},

		uninstallMix: function (mixId) {
			GM_provider.unInstall(mixId);
		},
		
		installMix: function (fileURI) {			
			for (var i=0; i<patterns.length; i+=1) {
				if ( fileURI.match( patterns[i] ) ) {
					var provider =  providersMap[patterns[i]];
					try {
						if (provider == null) {
							break;
						}
						provider.install(fileURI);
						return;
					}
					catch (e) {
						alert("WebShakes (provider error)  -  error occurred while trying to install " + fileURI + "\n error =" + e);
						return;
					};
				}
			}
			alert("WebShakes (Internal Error) - couldn't find a provider for file " + fileURI);
		},

		previewMix: function (fileURI) {
			for (var i=0; i<patterns.length; i+=1) {
				if ( fileURI.match( patterns[i] ) ) {
					var provider =  providersMap[patterns[i]];
					try {
						if (provider == null) {
							break;
						}
						provider.preview(fileURI);
						return;
					}
					catch (e) {
						alert("WebShakes (provider error)  -  error occured while trying to install " + fileURI + "\n error =" + e);
						return;
					};
				}
			}
			alert("WebShakes (Internal Error) - couldn't find a provider for file " + fileURI);
		},

		//----------------------------------------------
		// ---------  Provider Callback API   --------
		//----------------------------------------------

		/**
		* Install a mix
		* returns MixId installCallBack
		*/
		installCallback: function (mixId, fileURI) {
			alert("the requested file" + fileURI + " was successfully installed with mixId " + mixId);
		},
		
		/**
	  	  * Report that hits mix had unexpected behavior 
		  * level is on of {low, medium, high}
		  */
		reportProblem: function (mixId,  level) {
			// TODO shex implement
		},

		/**
		  * Request a temporary file with a specific content
		  * returns URI 
		  * throws OverQuataException  if granting request will cause to exceed the configured limit
		  */
		getTempFile: function(content) { 
			return null;
			// TODO shex implement
		}, 

		/**
		 * Make a synchronous call for a remote value
		 * Scope - namespace
		 * TTL - for each key, we keep the version which it was read
		 * returns string
		 */
		getGlobalValue: function (key) {
			return null;
			// TODO shex implement
		},
		 
		/**
		 * Make a synchronous call for a remote store value
		 * Scope - namespace
		 * throws OverQuataException, if granting request will cause to exceed the configured limit
		 * throws InvalidView if 
		 */
		setGlobalValue: function (key, value) {
			return null;
			// TODO shex implement
		},
		
		//----------------------------------------------
		// ---------  			      Internal    	  			   --------
		//----------------------------------------------
 
		
		// convert a single instance's method invocation to a function
		__bind: function(obj, method) {
			  if (!obj[method]) {
			    throw "method '" + method + "' does not exist on object '" + obj + "'";
			  }
			
			  var staticArgs = Array.prototype.splice.call(arguments, 2, arguments.length);
			
			  return function() {
			    // make a copy of staticArgs (don't modify it because it gets reused for every invocation).
			    var args = Array.prototype.slice.call(staticArgs);
			
			    // add all the new arguments
			    Array.prototype.push.apply(args, arguments);
			
			    // invoke the original function with the correct this obj and the combined
			    // list of static and dynamic arguments.
			    return obj[method].apply(obj, args);
			  };
		},
		
    };

    return obj;
  })();

// TODO shex, consider moving this code to be generated by the server (and then make webshakesIFrame local variable) 
var webshakesIFrameFullHeight;
var animationTargetSize;  
var webshakesIFrame; // This is the iframe which will comprise the html used for interaction with user


function animateOpenWindow() {
	var currentHeight = parseInt(webshakesIFrame.style.height);
	if(currentHeight > animationTargetSize){		
		webshakesIFrame.style.height = animationTargetSize + 'px';
		return;
	}
	else{
		webshakesIFrame.style.height = (currentHeight + 10) + 'px';	
		setTimeout(animateOpenWindow, 20);
	}
}

function animateMinimizeWindow() {

	var currentHeight = parseInt(webshakesIFrame.style.height);
	if(currentHeight < animationTargetSize){		
		return;
	}
	else{
		webshakesIFrame.style.height = (currentHeight - 10) + 'px';
		setTimeout(animateMinimizeWindow, 10);
	}
}

function animateCloseWindow() {

	var currentHeight = parseInt(webshakesIFrame.style.height);
	if(currentHeight < 10){		
		webshakesIFrame.style.display = 'none';
	}
	else{
		webshakesIFrame.style.height = (currentHeight - 10) + 'px';	
		setTimeout(animateCloseWindow, 10);
	}
}

function handleApplyMix() {
	var e = webshakesIFrame.contentWindow.document.getElementById('webshakesPreviewMix');
	var mixURI = e.getAttribute('mixURI');
	WebShakes.previewMix(mixURI);
	
	// small dialog layout
	animationTargetSize = 180;
	webshakesIFrameFullHeight = false;
	animateMinimizeWindow();
}

function handleToggleEnableMix() {
	try {
		var e = webshakesIFrame.contentWindow.document.getElementById('webshakesToggleEnableMix');
		var mixURI = e.getAttribute('mixURI');
		WebShakes.toggleEnableMix(mixURI);
	} 
	catch (e) {
		alert(e)
	}
}

function handleUninstallMix() {
	try {
		var e = webshakesIFrame.contentWindow.document.getElementById('webshakesUninstallMix');
		var mixURI = e.getAttribute('mixURI');
		WebShakes.uninstallMix(mixURI);
	} 
	catch (e) {
		alert(e)
	}
}

function handleInstallMix() {
	try {
		var e = webshakesIFrame.contentWindow.document.getElementById('webshakesInstallMix');
		var mixURI = e.getAttribute('mixURI');
		WebShakes.installMix(mixURI);
	}
	catch(e){ alert(e) }
}

/**
 * handle clicking on icon (status bar)
 * left-click starts search, right click shows the popup
 */
function webshakesClicked(aEvent) {
	
  if (aEvent.button == 0 || aEvent.button == 2) {
    //var script = aEvent.target.script;
    //if (!script) return;

    if (aEvent.button == 0) // left-click: search 
      	webshakes_Search()
    else // right-click: show the menu
      	webshakes_showMenu();
  }
}

// TODO shex, unite this code with search and manage
function webshakes_showMenu() {
	var action = 'menus/show';
	var viewedDocument = window.content.document;
	var getURI = 'http://localhost:3001/' + action
	var webShakesId = 'WebShakes.net'
	try {
		// position:fixed means stay fixed even the page scrolls. z-index keeps your iframe on top.
		// The remainder of the line smacks the panel into the bottom right corner, out of your way.
		// Overflow (in combination with the setTimeout) ensures the iframe fits your entire panel.
		var css = 'position:fixed; z-index:9999; bottom:0px; right:0px; border:0; margin:0; padding:0; ' +
		'overflow:hidden; height:0; width:220px; display:normal'
		
		webshakesIFrame = viewedDocument.getElementById(webShakesId);
		if (webshakesIFrame == null) {
			webshakesIFrame = viewedDocument.createElement('iframe');
			webshakesIFrame.setAttribute('id', webShakesId);
			viewedDocument.body.appendChild(webshakesIFrame);
		}
		webshakesIFrame.setAttribute('style', css);
		webshakesIFrame.src = getURI;
		
		// main dialog layout
		animationTargetSize = 343;
		webshakesIFrameFullHeight = true;
		
		// Make sure Firefox initializes the DOM before we try to use it.
		webshakesIFrame.addEventListener("load", function(aEvent){
			
			//viewedDocument.getElementByID('small_dialog').focus();
			animateOpenWindow();
			webshakesIFrame.contentWindow.document.addEventListener("webshakes-close-event", animateCloseWindow, false);
			webshakesIFrame.contentWindow.document.addEventListener('webshakes-search-menu-clicked-event', webshakes_Search, false);
			webshakesIFrame.contentWindow.document.addEventListener('webshakes-manage-installed-menu-clicked-event', webshakes_manageInstalled, false);
			
		}, false);
	} 
	catch (e) {
		alert(e);
	}
	
}

function webshakes_manageInstalled() {
	var action = 'opinion/show?all=true';
	var getURI = 'http://localhost:3001/' + action
	webshakes_addDialogToDisplayedPage(getURI, "manage");
}

function webshakes_Search() {
	var action = 'search';
	var userURI = window.content.document.location;
	var params = '?url=' + encodeURIComponent(userURI)
	var getURI = 'http://localhost:3001/' + action + params;
    webshakes_addDialogToDisplayedPage(getURI, "search");
}

function webshakes_addDialogToDisplayedPage(getURI, action) {
	var viewedDocument = window.content.document;
	
	var webShakesId = 'WebShakes.net'
	try {
		// position:fixed means stay fixed even the page scrolls. z-index keeps your iframe on top.
		// the remainder of the line smacks the panel into the bottom right corner, out of your way.
		// overflow (in combination with the setTimeout) ensures the iframe fits your entire panel.
		var css = 'position:fixed; z-index:9999; bottom:0px; right:0; border:0; margin:0; padding:0; ' +
		   			   'overflow:hidden; height:0px; width:415px; display:normal'
		
		webshakesIFrame = viewedDocument.getElementById(webShakesId);
		if (webshakesIFrame == null) {
			webshakesIFrame = viewedDocument.createElement('iframe');
			webshakesIFrame.setAttribute('id', webShakesId);
			viewedDocument.body.appendChild(webshakesIFrame);
		}
		webshakesIFrame.setAttribute('style', css);
		webshakesIFrame.src = getURI;
		
		// main dialog layout
		animationTargetSize = 445;
		webshakesIFrameFullHeight = true;
		
		// Make sure Firefox initializes the DOM before we try to use it.
		webshakesIFrame.addEventListener("load", function(aEvent){
			if (webshakesIFrameFullHeight) {
				animateOpenWindow();
			}			
			
			switch(action) {
				case "search":
				    webshakes_addEventListenersForSearch();
					break;
				case "manage":
				    webshakes_addEventListenersForManage();
					break;
			}
			
		}, false);
	} 
	catch (e) {
		alert(e);
	}
	
	//		It is highly recommended to check the source of the event  
	// 		(via event.target.ownerDocument.location) and make your extension ignore  
	//      any events from pages not from your server.	
}

function webshakes_addEventListenersForManage() {
	webshakesIFrame.contentWindow.document.body.addEventListener("webshakes-close-event", animateCloseWindow, false);
	webshakesIFrame.contentWindow.document.body.addEventListener("webshakes-uninstall-mix-event", handleUninstallMix, false);
	webshakesIFrame.contentWindow.document.body.addEventListener("webshakes-toggle-enable-mix-event", handleToggleEnableMix, false);
	// webshakesIFrame.contentWindow.document.addEventListener("webshakes-apply-mix-event", handleApplyMix, false);	
}

function webshakes_addEventListenersForSearch() {
	webshakesIFrame.contentWindow.document.body.addEventListener("webshakes-close-event", animateCloseWindow, false, true);
	webshakesIFrame.contentWindow.document.body.addEventListener("webshakes-install-mix-event", handleInstallMix, false);
	webshakesIFrame.contentWindow.document.body.addEventListener("webshakes-apply-mix-event", handleApplyMix, false);
}
